name: revue_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  envied: ^0.3.0+3
  flutter_hooks: ^0.18.6
  flutter_highlight: ^0.7.0
  flutter_markdown: ^0.6.15
  highlight: ^0.7.0
  markdown: ^7.1.0
  google_fonts: ^4.0.3
  markdown_widget: ^2.2.0
  dio: ^5.1.2
  path: ^1.8.3
  path_provider: ^2.0.15
  flutter_adaptive_scaffold: ^0.1.4
  github: ^9.14.0
  flutter_riverpod: ^2.3.6
  hooks_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  equatable: ^2.0.5
  cached_network_image: ^3.2.3
  material_design_icons_flutter: ^6.0.7096
  flutter_spinkit: ^5.2.0
  freezed: ^2.3.4
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  intl: ^0.18.1
  sp_ai_simple_bpe_tokenizer: ^0.0.1+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  envied_generator: ^0.3.0+3
  build_runner: ^2.4.4
  custom_lint: ^0.4.0
  riverpod_lint: ^1.3.2
  riverpod_generator: ^2.2.3
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true
